### ISSUE TITLE
GUI | Meal Overview

### ISSUE THREAD

**Issue by rhefner1** [cookomatic/cookomatic-app#13]
**Acceptance Test**: Demonstrate functioning interface according to mockups and taking user feedback into account.

---
Depends on #6

**Comment by amham17** [comment]
Create a screen that shows the dishes the user wants to make, along with their collective ingredients, their instructions, tools, etc. 

This screen should also allow the user to remove a dish from the meal, or begin cooking. 

----
**Acceptance Test**: Determine that a user can add our 2 dishes to form a meal, and correctly view their combined information. Also determine that the user can remove a dish from this screen.
